global:
  resolve_timeout: 5m  # ì•ŒëŒ(ì—ëŸ¬ìƒí™©)ì´ resolved ìƒíƒœë¡œ ë°”ë€ í›„, í•´ì œ ì²˜ë¦¬ê¹Œì§€ ëŒ€ê¸° ì‹œê°„

route:
  group_by: ['severity', 'alertname']
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 5m
  receiver: 'slack-warning'
  routes:
    # error - ì¦‰ì‹œ ë°œì†¡
    - match:
        severity: critical
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 30m
      receiver: 'slack-error'
    
    # warning
    - match:
        severity: warning
      group_wait: 10s
      group_interval: 30s  
      repeat_interval: 1h
      receiver: 'slack-warning'

receivers:
  - name: slack-error
    slack_configs:
      - channel: '#error-alerts'     # error ì „ìš© Slack ì±„ë„
        send_resolved: true
        username: 'MonitoringBot'
        title: '{{ .CommonAnnotations.summary }}'
        text: |
          ğŸš¨ *[ERROR]*
          {{ .CommonAnnotations.description }}
        
          *ìƒì„¸ ì •ë³´:*
          â€¢ ğŸ–¥ï¸ *host*: {{ .CommonLabels.host }}
          â€¢ ğŸ“‹ *filename*: {{ .CommonLabels.filename }}
        api_url: 'https://hooks.slack.com/services/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'  # Webhook URL

  - name: slack-warning
    slack_configs:
      - channel: '#warning-alerts'   # warning ì „ìš© Slack ì±„ë„
        send_resolved: true
        username: 'MonitoringBot'
        title: '{{ .CommonAnnotations.summary }}'
        text: |
          âš ï¸ *[WARNING]* 
          {{ .CommonAnnotations.description }}
        
          *ìƒì„¸ ì •ë³´:*
          â€¢ ğŸ–¥ï¸ *host*: {{ .CommonLabels.host }}
          â€¢ ğŸ“‹ *filename*: {{ .CommonLabels.filename }}
        api_url: 'https://hooks.slack.com/services/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'  # Webhook URL
